version: '3.1'

services:

  jogatina:
    build: .
    image: jogatina
    container_name: jogatina
    hostname: jogatina
    restart: always
    volumes:
      - ./servicos/jogatina:/servico
    command: python3 /servico/servico.py
    ports:
      - 5001:5000
  sistemas:
    build: .
    image: sistemas
    container_name: sistemas
    hostname: sistemas
    restart: always
    volumes:
      - ./servicos/sistemas:/servico
    command: python3 /servico/servico.py
    ports:
      - 5002:5000